### ISSUE TITLE
Filter also by activation events

### ISSUE THREAD

**Issue by cosminalco** [fabiospampinato/vscode-commands#4]
Thank for this awesome extension. On suggestion to make it complete, although I don't know if it can be done through the current API.  

`vscode-commands` besides the custom filters `filterLanguageRegex` and `filterFileRegex`  should also filter by `activationEvents` from  `package.json`  by default. 

E.g. Show the button `      {
        "text": "$(sync)",
        "command": "extension.browserSyncRefreshSidePanel",
        "tooltip": "Refresh sidepanel"
      }` only after running `extension.browserSyncProxyAtPanel`  because that's what [BrowserSync](https://marketplace.visualstudio.com/items?itemName=jasonlhy.vscode-browser-sync) has in [`activationEvents`](https://github.com/Jasonlhy/VSCode-Browser-Sync/blob/master/package.json#L13). Hide the button if running `extension.exitAll` because the extension is not active anymore.

**Comment by fabiospampinato** [comment]
It would be a nice addition, but it's not possible to listen on other extensions' commands, the docs state:

> Registering a command with an existing command identifier twice will cause an error.

So I don't think this can be achieved "easily", there are some possible workarounds, but it wouldn't work exactly the same and it would be kind of a mess to configure. 🤔

**Comment by cosminalco** [comment]
I dug up the API and found `vscode.extensions.getExtension` . `vscode-commands` could have a filter `"filterExtension":"jasonlhy.vscode-browser-sync"`. Will work for when creating a button. I test it and `vscode.extensions.getExtension('jasonlhy.vscode-browser-sync').isActive` returns the correct Boolean. 

But I couldn't find an event listener for later to show/hide the button when an extension gets activated/deactivated, so we're back from where we started.

> there are some possible workarounds

I'm curious about those workarounds, the directions you are thinking about, maybe I'll create a simple extension for myself for those kind of buttons before going to plan C: adding the button directly in `jasonlhy.vscode-browser-sync` extension. Now I'm on plan B and I'll probably stick with it: leave it as it is.

**Comment by fabiospampinato** [comment]
> I'm curious about those workarounds, the directions you are thinking about

1. `vscode-commands` could add a `toggleButton` command, which you would call and pass the id (text?) of the button you want to toggle as an argument.
2. Instead of using `vscode-browser-sync`'s commands directly you could wrap them in [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros) that will automatically call that hypothetical `toggleButton` command for you.
3. Those external extensions could emit events by calling the `vscode-commands.onCommand` command or something.
4. If those external extensions set some custom context keys (`vscode.commands.executeCommand ( 'setContext', 'browser-sync-active', true | false )`) maybe that would be enough for implementing this.
5. If those external extensions add a statusbar item or something you could detect that via some custom JS injected via [Custom CSS and JS loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css), then maybe you could execute that `toggleButton` command automatically.

**Comment by fabiospampinato** [comment]
Closing as this sounds like the perfect use case for context expressions, which are not supported yet, but we are tracking that here: #7
