### ISSUE TITLE
Filter for active task

### ISSUE THREAD

**Issue by hediet** [fabiospampinato/vscode-commands#8]
It would be great to be able to have a filter based on whether a given task is running (e.g. `watch`).
This way, I can have a start and a stop command for a specific task, which are only visible when they actually make sense.

**Comment by hediet** [comment]
Maybe you could even add a separate type for commands - `tasks` that toggle between run and terminate of a given task:
```json
        {
            "alignment": "left",
            "priority": -1000,
            "text": "Start tsc watch"
            "runningText": "Stop tsc watch ",
            "task": "tsc watch",
        }
```

**Comment by fabiospampinato** [comment]
I'm not sure there's any API for detecting this. Plus I have 0 interest whatsoever in tasks.

If somebody would like to submit a PR for this I'd be happy to consider it.

**Comment by hediet** [comment]
Why don't you like tasks? :)

**Comment by fabiospampinato** [comment]
I already have the concept of a terminal and terminal commands, I have no need for tasks.

**Comment by fabiospampinato** [comment]
Yeah closing this as I really couldn't care less about tasks.

**Comment by hediet** [comment]
In the meantime, I created [this extension](https://marketplace.visualstudio.com/items?itemName=hediet.tasks-statusbar) to solve my use case.

You should have a second look at tasks! It is nice that VS Code knows if they are running or not.

**Comment by fabiospampinato** [comment]
I don't know they are just completely useless to me honestly, perhaps harmful even, considering that they occupy some space in your brain since you must know about them and also they suck up some development resources. Even if there was something interesting about them should I implement the thing I would use them for in a way that only people using vscode can use too? Probably not.
